# Generated by Django 5.1.6 on 2025-03-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMapp', '0001_added_new_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.DeleteModel(
            name='Assign_Task',
        ),
    ]
