# Generated by Django 5.1.6 on 2025-03-03 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMapp', '0002_alter_task_status_delete_assign_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(default='LOW', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='project_id',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='TMapp.project'),
        ),
    ]
